// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace StrategyGame
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DistrictDestroyedEvent : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_8(); }
  public static DistrictDestroyedEvent GetRootAsDistrictDestroyedEvent(ByteBuffer _bb) { return GetRootAsDistrictDestroyedEvent(_bb, new DistrictDestroyedEvent()); }
  public static DistrictDestroyedEvent GetRootAsDistrictDestroyedEvent(ByteBuffer _bb, DistrictDestroyedEvent obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DistrictDestroyedEvent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ushort Version { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)1; } }
  public string City { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCityBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetCityBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetCityArray() { return __p.__vector_as_array<byte>(6); }
  public string District { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDistrictBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetDistrictBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetDistrictArray() { return __p.__vector_as_array<byte>(8); }
  public int LostPopulation { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<StrategyGame.DistrictDestroyedEvent> CreateDistrictDestroyedEvent(FlatBufferBuilder builder,
      ushort version = 1,
      StringOffset cityOffset = default(StringOffset),
      StringOffset districtOffset = default(StringOffset),
      int lostPopulation = 0) {
    builder.StartTable(4);
    DistrictDestroyedEvent.AddLostPopulation(builder, lostPopulation);
    DistrictDestroyedEvent.AddDistrict(builder, districtOffset);
    DistrictDestroyedEvent.AddCity(builder, cityOffset);
    DistrictDestroyedEvent.AddVersion(builder, version);
    return DistrictDestroyedEvent.EndDistrictDestroyedEvent(builder);
  }

  public static void StartDistrictDestroyedEvent(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddVersion(FlatBufferBuilder builder, ushort version) { builder.AddUshort(0, version, 1); }
  public static void AddCity(FlatBufferBuilder builder, StringOffset cityOffset) { builder.AddOffset(1, cityOffset.Value, 0); }
  public static void AddDistrict(FlatBufferBuilder builder, StringOffset districtOffset) { builder.AddOffset(2, districtOffset.Value, 0); }
  public static void AddLostPopulation(FlatBufferBuilder builder, int lostPopulation) { builder.AddInt(3, lostPopulation, 0); }
  public static Offset<StrategyGame.DistrictDestroyedEvent> EndDistrictDestroyedEvent(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<StrategyGame.DistrictDestroyedEvent>(o);
  }
  public static void FinishDistrictDestroyedEventBuffer(FlatBufferBuilder builder, Offset<StrategyGame.DistrictDestroyedEvent> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedDistrictDestroyedEventBuffer(FlatBufferBuilder builder, Offset<StrategyGame.DistrictDestroyedEvent> offset) { builder.FinishSizePrefixed(offset.Value); }
}


}
