// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace StrategyGame
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct EconomyUpdatedEvent : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_8(); }
  public static EconomyUpdatedEvent GetRootAsEconomyUpdatedEvent(ByteBuffer _bb) { return GetRootAsEconomyUpdatedEvent(_bb, new EconomyUpdatedEvent()); }
  public static EconomyUpdatedEvent GetRootAsEconomyUpdatedEvent(ByteBuffer _bb, EconomyUpdatedEvent obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EconomyUpdatedEvent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ushort Version { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)1; } }
  public string Country { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCountryBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetCountryBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetCountryArray() { return __p.__vector_as_array<byte>(6); }
  public double NewBudget { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : (double)0.0; } }
  public double Gdp { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : (double)0.0; } }

  public static Offset<StrategyGame.EconomyUpdatedEvent> CreateEconomyUpdatedEvent(FlatBufferBuilder builder,
      ushort version = 1,
      StringOffset countryOffset = default(StringOffset),
      double newBudget = 0.0,
      double gdp = 0.0) {
    builder.StartTable(4);
    EconomyUpdatedEvent.AddGdp(builder, gdp);
    EconomyUpdatedEvent.AddNewBudget(builder, newBudget);
    EconomyUpdatedEvent.AddCountry(builder, countryOffset);
    EconomyUpdatedEvent.AddVersion(builder, version);
    return EconomyUpdatedEvent.EndEconomyUpdatedEvent(builder);
  }

  public static void StartEconomyUpdatedEvent(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddVersion(FlatBufferBuilder builder, ushort version) { builder.AddUshort(0, version, 1); }
  public static void AddCountry(FlatBufferBuilder builder, StringOffset countryOffset) { builder.AddOffset(1, countryOffset.Value, 0); }
  public static void AddNewBudget(FlatBufferBuilder builder, double newBudget) { builder.AddDouble(2, newBudget, 0.0); }
  public static void AddGdp(FlatBufferBuilder builder, double gdp) { builder.AddDouble(3, gdp, 0.0); }
  public static Offset<StrategyGame.EconomyUpdatedEvent> EndEconomyUpdatedEvent(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<StrategyGame.EconomyUpdatedEvent>(o);
  }
  public static void FinishEconomyUpdatedEventBuffer(FlatBufferBuilder builder, Offset<StrategyGame.EconomyUpdatedEvent> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedEconomyUpdatedEventBuffer(FlatBufferBuilder builder, Offset<StrategyGame.EconomyUpdatedEvent> offset) { builder.FinishSizePrefixed(offset.Value); }
}


}
