// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace StrategyGame
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct MajorInfrastructureBuiltEvent : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_8(); }
  public static MajorInfrastructureBuiltEvent GetRootAsMajorInfrastructureBuiltEvent(ByteBuffer _bb) { return GetRootAsMajorInfrastructureBuiltEvent(_bb, new MajorInfrastructureBuiltEvent()); }
  public static MajorInfrastructureBuiltEvent GetRootAsMajorInfrastructureBuiltEvent(ByteBuffer _bb, MajorInfrastructureBuiltEvent obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MajorInfrastructureBuiltEvent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ushort Version { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)1; } }
  public string City { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCityBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetCityBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetCityArray() { return __p.__vector_as_array<byte>(6); }
  public string InfrastructureType { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetInfrastructureTypeBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetInfrastructureTypeBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetInfrastructureTypeArray() { return __p.__vector_as_array<byte>(8); }
  public double Value { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : (double)0.0; } }

  public static Offset<StrategyGame.MajorInfrastructureBuiltEvent> CreateMajorInfrastructureBuiltEvent(FlatBufferBuilder builder,
      ushort version = 1,
      StringOffset cityOffset = default(StringOffset),
      StringOffset infrastructureTypeOffset = default(StringOffset),
      double value = 0.0) {
    builder.StartTable(4);
    MajorInfrastructureBuiltEvent.AddValue(builder, value);
    MajorInfrastructureBuiltEvent.AddInfrastructureType(builder, infrastructureTypeOffset);
    MajorInfrastructureBuiltEvent.AddCity(builder, cityOffset);
    MajorInfrastructureBuiltEvent.AddVersion(builder, version);
    return MajorInfrastructureBuiltEvent.EndMajorInfrastructureBuiltEvent(builder);
  }

  public static void StartMajorInfrastructureBuiltEvent(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddVersion(FlatBufferBuilder builder, ushort version) { builder.AddUshort(0, version, 1); }
  public static void AddCity(FlatBufferBuilder builder, StringOffset cityOffset) { builder.AddOffset(1, cityOffset.Value, 0); }
  public static void AddInfrastructureType(FlatBufferBuilder builder, StringOffset infrastructureTypeOffset) { builder.AddOffset(2, infrastructureTypeOffset.Value, 0); }
  public static void AddValue(FlatBufferBuilder builder, double value) { builder.AddDouble(3, value, 0.0); }
  public static Offset<StrategyGame.MajorInfrastructureBuiltEvent> EndMajorInfrastructureBuiltEvent(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<StrategyGame.MajorInfrastructureBuiltEvent>(o);
  }
  public static void FinishMajorInfrastructureBuiltEventBuffer(FlatBufferBuilder builder, Offset<StrategyGame.MajorInfrastructureBuiltEvent> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedMajorInfrastructureBuiltEventBuffer(FlatBufferBuilder builder, Offset<StrategyGame.MajorInfrastructureBuiltEvent> offset) { builder.FinishSizePrefixed(offset.Value); }
}


}
