// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace StrategyGame
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct PopulationUpdatedEvent : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_8(); }
  public static PopulationUpdatedEvent GetRootAsPopulationUpdatedEvent(ByteBuffer _bb) { return GetRootAsPopulationUpdatedEvent(_bb, new PopulationUpdatedEvent()); }
  public static PopulationUpdatedEvent GetRootAsPopulationUpdatedEvent(ByteBuffer _bb, PopulationUpdatedEvent obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PopulationUpdatedEvent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ushort Version { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)1; } }
  public int EntityId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int NewPopulation { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<StrategyGame.PopulationUpdatedEvent> CreatePopulationUpdatedEvent(FlatBufferBuilder builder,
      ushort version = 1,
      int entityId = 0,
      int newPopulation = 0) {
    builder.StartTable(3);
    PopulationUpdatedEvent.AddNewPopulation(builder, newPopulation);
    PopulationUpdatedEvent.AddEntityId(builder, entityId);
    PopulationUpdatedEvent.AddVersion(builder, version);
    return PopulationUpdatedEvent.EndPopulationUpdatedEvent(builder);
  }

  public static void StartPopulationUpdatedEvent(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddVersion(FlatBufferBuilder builder, ushort version) { builder.AddUshort(0, version, 1); }
  public static void AddEntityId(FlatBufferBuilder builder, int entityId) { builder.AddInt(1, entityId, 0); }
  public static void AddNewPopulation(FlatBufferBuilder builder, int newPopulation) { builder.AddInt(2, newPopulation, 0); }
  public static Offset<StrategyGame.PopulationUpdatedEvent> EndPopulationUpdatedEvent(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<StrategyGame.PopulationUpdatedEvent>(o);
  }
  public static void FinishPopulationUpdatedEventBuffer(FlatBufferBuilder builder, Offset<StrategyGame.PopulationUpdatedEvent> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedPopulationUpdatedEventBuffer(FlatBufferBuilder builder, Offset<StrategyGame.PopulationUpdatedEvent> offset) { builder.FinishSizePrefixed(offset.Value); }
}


}
